# Generated by Django 6.0 on 2026-02-26 17:14

from django.db import migrations


from django.db import migrations

def create_grades(apps, schema_editor):
    Grade = apps.get_model("marketplace", "Grade")
    for i in range(1, 13):
        Grade.objects.get_or_create(name=f"Grade {i}")

class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0001_initial.py"),
    ]

    operations = [
        migrations.RunPython(create_grades),
    ]